# Generated by Django 2.2.20 on 2021-05-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_borrowrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='借书时间'),
        ),
    ]
