# Generated by Django 2.2.20 on 2021-05-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210522_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='is_return',
            field=models.IntegerField(default=0, verbose_name='是否归还'),
        ),
    ]
